export const SALE_MODULES = {
  'land-sales': {
    endpoint: 'land-sales',
    module: 'land_sale',
    label: 'Land Sale',
    title: 'all_land_sales',
    subtitle: 'manage_land_sales',
    addLabel: 'add_land_sale',
    amountLabel: 'sale_price',
    detailsKey: 'land_sale_details',
    amountField: 'sale_price',
    hasMeters: true,
    hasCommission: true,
    hasNotes: false,
    searchPlaceholder: 'search_land_sales',
    emptyMessage: 'no_land_sales_found',
    deleteMessage: 'delete_land_sale',
  },
  'house-rentals': {
    endpoint: 'house-rentals',
    module: 'house_rental',
    label: 'House Rental',
    title: 'all_house_rentals',
    subtitle: 'manage_house_rentals',
    addLabel: 'add_house_rental',
    amountLabel: 'rent_amount',
    detailsKey: 'house_rental_details',
    amountField: 'rent_amount',
    perMonth: true,
    hasCommission: true,
    searchPlaceholder: 'search_house_rentals',
    emptyMessage: 'no_house_rentals_found',
    deleteMessage: 'delete_house_rental',
  },
  'house-sales': {
    endpoint: 'house-sales',
    module: 'house_sale',
    label: 'House Sale',
    title: 'all_house_sales',
    subtitle: 'manage_house_sales',
    addLabel: 'add_house_sale',
    amountLabel: 'sale_price',
    detailsKey: 'house_sale_details',
    amountField: 'sale_price',
    hasCommission: true,
    searchPlaceholder: 'search_house_sales',
    emptyMessage: 'no_house_sales_found',
    deleteMessage: 'delete_house_sale',
  },
};

export const PAYMENT_METHODS = ['cash', 'bank_transfer', 'installment'];
